---
fixtures:
  repositories:
    stdlib:
      ref: "v6.3.0"
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
    mysql:
      ref: "v10.6.0"
      repo: "https://github.com/puppetlabs/puppetlabs-mysql"
  symlinks:
    vision_prometheus: '#{source_dir}'
